<a href="https://colab.research.google.com/github/THESANNN/UAS_4212111041/blob/main/UAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NAMA : HASANUL MUHAMMAD YUNUS

NIM : 4212111041

KELAS : MEKATRONIKA 5B MALAM

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score
from skimage.feature import hog

# Muat dataset MNIST
digits = datasets.load_digits()

# Ekstrak fitur HOG dan ratakan gambar
hog_features = []
for img in digits.images:
    fd, hog_image = hog(img, orientations=8, pixels_per_cell=(2, 2), cells_per_block=(1, 1), visualize=True)
    hog_features.append(fd)

hog_features = np.array(hog_features)
labels = digits.target

# Bagi dataset menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(hog_features, labels, test_size=0.3, random_state=42)

# Latih klasifikasi Support Vector Machine (SVM)
svm_classifier = SVC()
svm_classifier.fit(X_train, y_train)

# Prediksi
y_pred = svm_classifier.predict(X_test)

# Evaluasi klasifikasi
akurasi = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')

print(f"Akurasi: {akurasi*100:.2f}%")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Precision: {precision*100:.2f}%")

Akurasi: 96.48%
Confusion Matrix:
[[53  0  0  0  0  0  0  0  0  0]
 [ 0 47  2  0  0  0  0  0  1  0]
 [ 0  0 45  1  0  0  0  0  1  0]
 [ 0  0  2 47  0  1  0  0  0  4]
 [ 0  0  0  0 58  0  0  2  0  0]
 [ 0  0  0  0  0 65  1  0  0  0]
 [ 1  0  0  0  0  0 52  0  0  0]
 [ 0  0  0  0  1  0  0 54  0  0]
 [ 0  0  0  0  0  0  0  0 43  0]
 [ 0  0  0  0  0  0  0  0  2 57]]
Precision: 96.58%
